package javaapplication21;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import static javaapplication21.TournamentSimulator.parseNewCompetitor;
import static javaapplication21.TournamentSimulator.parseNewJudge;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author katidid
 */
public class EditTournament extends javax.swing.JFrame {
    TournamentMenu tournMenu;
    TourneyController controller = new TourneyController();
    String currentTournamentName;
    /**
     * Creates new form EditTournament
     */
    public EditTournament(TournamentMenu in, Tournament currentTournament) {
        initComponents();
        populateListBox();
        populateJudgeListBox();
        getContentPane().setBackground(Color.darkGray);
        tournMenu = in;
        currentTournamentName = currentTournament.getName();
    }
    /**
     * 
     */
    private void populateListBox()
    {
        File outFile = new File("/Users/katidid/desktop/COMPETITORS.txt");
        if (SelectListOfComps.getModel().getSize() == 0)
        {
            try (BufferedReader reader = new BufferedReader(new FileReader(outFile))) 
            {
                String line = null;
                while ((line = reader.readLine()) != null) 
                {
                    Competitor newCompetitor = parseNewCompetitor(line);
                    
                    ((DefaultListModel)SelectListOfComps.getModel()).addElement(newCompetitor);    
                }
            } 
            catch (IOException x) 
            {
                System.err.format("IOException: %s%n", x);
            }
        }
    }
    /**
     * 
     */
    private void populateJudgeListBox()
    {
        File outFile = new File("/Users/katidid/desktop/JUDGES.txt");
        
        if (SelectListOfJudges.getModel().getSize() == 0)
        {
            try (BufferedReader reader = new BufferedReader(new FileReader(outFile))) 
            {
                String line = null;
                while ((line = reader.readLine()) != null) 
                {
                    Judge newJ = parseNewJudge(line);
                    
                    ((DefaultListModel)SelectListOfJudges.getModel()).addElement(newJ);
                    
                }
            } 
            catch (IOException x) 
            {
                System.err.format("IOException: %s%n", x);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListOfCompetitors = new javax.swing.JScrollPane();
        SelectListOfComps = new javax.swing.JList();
        AddToTournament = new javax.swing.JButton();
        ListOfCompetitors1 = new javax.swing.JScrollPane();
        SelectListOfJudges = new javax.swing.JList();
        MessageLabel = new javax.swing.JLabel();
        AddedCompsPane = new javax.swing.JScrollPane();
        AddedComps = new javax.swing.JList();
        AddedCompsPane1 = new javax.swing.JScrollPane();
        AddedJudges = new javax.swing.JList();
        backButton = new javax.swing.JButton();
        AddJudgesToTournament = new javax.swing.JButton();
        compLabel = new javax.swing.JLabel();
        compLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectListOfComps.setModel(new DefaultListModel<Competitor>()
            {
                public int getSize(){
                    return controller.getNumComps();
                }
                public Competitor getElementAt(int i) {
                    return controller.getCompetitor(i);
                }
                public void addElement(Competitor e) {
                    super.addElement(e);
                    controller.addStu(e);
                }
                public void add(int i, Competitor e) {
                    super.add(i,e);
                    controller.addStu(e);
                }
            });
            ListOfCompetitors.setViewportView(SelectListOfComps);

            AddToTournament.setBackground(new java.awt.Color(255, 102, 102));
            AddToTournament.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
            AddToTournament.setText("Add Names to Tournament");
            AddToTournament.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AddToTournamentActionPerformed(evt);
                }
            });

            SelectListOfJudges.setModel(new DefaultListModel<Judge>()
                {
                    public int getSize(){
                        return controller.getNumJudges();
                    }
                    public Judge getElementAt(int i) {
                        return controller.getJudge(i);
                    }
                    public void addElement(Judge e) {
                        super.addElement(e);
                        controller.addJudge(e);
                    }
                    public void add(int i, Judge e) {
                        super.add(i,e);
                        controller.addJudge(e);
                    }
                });
                ListOfCompetitors1.setViewportView(SelectListOfJudges);

                MessageLabel.setForeground(new java.awt.Color(255, 0, 0));
                MessageLabel.setText("MessageLabel");

                AddedComps.setModel(new DefaultListModel<Competitor>()
                    {
                        public void addElement(Competitor e) {
                            super.addElement(e);
                        }
                        public void add(int i, Competitor e) {
                            super.add(i,e);
                        }
                    });
                    AddedCompsPane.setViewportView(AddedComps);

                    AddedJudges.setModel(new DefaultListModel<Judge>()
                        {
                            public void addElement(Judge e) {
                                super.addElement(e);
                            }
                            public void add(int i, Judge e) {
                                super.add(i,e);
                            }
                        });
                        AddedCompsPane1.setViewportView(AddedJudges);

                        backButton.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
                        backButton.setText("DONE");
                        backButton.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                backButtonActionPerformed(evt);
                            }
                        });

                        AddJudgesToTournament.setBackground(new java.awt.Color(255, 102, 102));
                        AddJudgesToTournament.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
                        AddJudgesToTournament.setText("Add Names to Tournament");
                        AddJudgesToTournament.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AddJudgesToTournamentActionPerformed(evt);
                            }
                        });

                        compLabel.setFont(new java.awt.Font("Cochin", 2, 24)); // NOI18N
                        compLabel.setForeground(new java.awt.Color(255, 255, 255));
                        compLabel.setText("Competitors");

                        compLabel1.setFont(new java.awt.Font("Cochin", 2, 24)); // NOI18N
                        compLabel1.setForeground(new java.awt.Color(255, 255, 255));
                        compLabel1.setText("Judges");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddedCompsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                            .addComponent(AddToTournament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ListOfCompetitors))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ListOfCompetitors1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                            .addComponent(AddedCompsPane1)
                                            .addComponent(AddJudgesToTournament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(17, 17, 17))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(compLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(compLabel1)
                                .addGap(109, 109, 109))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backButton)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(compLabel)
                                    .addComponent(compLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddToTournament)
                                    .addComponent(AddJudgesToTournament))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ListOfCompetitors1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ListOfCompetitors, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddedCompsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddedCompsPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(MessageLabel)
                                .addContainerGap())
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     */
    private void AddToTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToTournamentActionPerformed
        ArrayList<Competitor> selectedComps = new ArrayList <Competitor>();
        int numSelections = SelectListOfComps.getSelectedIndices().length; // how many Competitors the user selected
        int[] selectedIndices = new int[numSelections]; // which ones were selected
        //MessageLabel.setText("" + numThings);
        for (int i = 0; i < numSelections; i++)
        {
            selectedIndices[i] =  SelectListOfComps.getSelectedIndices()[i]; // get which indices were selected
        }
        int whereSelectedIs;
        for (int i = 0; i < numSelections; i++)
        {
            whereSelectedIs = selectedIndices[i];
            Competitor newComp = (Competitor) SelectListOfComps.getModel().getElementAt(whereSelectedIs);
            selectedComps.add(newComp);
        }

        File tourneyCompOutFile = new File("/Users/katidid/desktop/"+currentTournamentName+ "_TOURNAMENTC.txt");

          
        try
        {
            FileWriter writer = new FileWriter(tourneyCompOutFile, true);
            try
            {
                for (int i = 0; i < selectedComps.size(); i++)
                {
                    writer.write(selectedComps.get(i).toString() + "\n");
                    ((DefaultListModel)AddedComps.getModel()).addElement(selectedComps.get(i));
                }
            }
            catch(IOException ex)
            {
                MessageLabel.setText("Didn't output.");
            }
            writer.close();
        }
        catch(IOException ex)
        {
            MessageLabel.setText("Didn't make file");
        }
        
    }//GEN-LAST:event_AddToTournamentActionPerformed
/**
 * 
 * @param evt 
 */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        tournMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void AddJudgesToTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJudgesToTournamentActionPerformed
        ArrayList<Judge> selectedComps = new ArrayList <Judge>();
        int numSelections = SelectListOfJudges.getSelectedIndices().length; // how many Competitors the user selected
        int[] selectedIndices = new int[numSelections]; // which ones were selected
        //MessageLabel.setText("" + numThings);
        for (int i = 0; i < numSelections; i++)
        {
            selectedIndices[i] =  SelectListOfJudges.getSelectedIndices()[i]; // get which indices were selected
        }
        int whereSelectedIs;
        for (int i = 0; i < numSelections; i++)
        {
            whereSelectedIs = selectedIndices[i];
            Judge newComp = (Judge) SelectListOfJudges.getModel().getElementAt(whereSelectedIs);
            selectedComps.add(newComp);
        }

        File tourneyJudgeOutFile = new File("/Users/katidid/desktop/"+currentTournamentName+ "_TOURNAMENTJ.txt");

          
        try
        {
            FileWriter writer = new FileWriter(tourneyJudgeOutFile, true);
            try
            {
                for (int i = 0; i < selectedComps.size(); i++)
                {
                    writer.write(selectedComps.get(i).toString() + "\n");
                    ((DefaultListModel)AddedJudges.getModel()).addElement(selectedComps.get(i));
                }
            }
            catch(IOException ex)
            {
                MessageLabel.setText("Didn't output.");
            }
            writer.close();
        }
        catch(IOException ex)
        {
            MessageLabel.setText("Didn't make file");
        }
    }//GEN-LAST:event_AddJudgesToTournamentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJudgesToTournament;
    private javax.swing.JButton AddToTournament;
    private javax.swing.JList AddedComps;
    private javax.swing.JScrollPane AddedCompsPane;
    private javax.swing.JScrollPane AddedCompsPane1;
    private javax.swing.JList AddedJudges;
    private javax.swing.JScrollPane ListOfCompetitors;
    private javax.swing.JScrollPane ListOfCompetitors1;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JList SelectListOfComps;
    private javax.swing.JList SelectListOfJudges;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel compLabel;
    private javax.swing.JLabel compLabel1;
    // End of variables declaration//GEN-END:variables
}
