/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import static javaapplication21.TournamentSimulator.parseNewJudge;
import javax.swing.DefaultListModel;

/**
 *
 * @author katidid
 */
public class NewTournament extends javax.swing.JFrame {
    Menu firstMenu;
    /**
     * Creates new form NewTournament
     */
    public NewTournament(Menu in) {
        initComponents();
        getContentPane().setBackground(Color.darkGray);
        firstMenu = in;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewTournamentButton = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        LocationTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        MessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewTournamentButton.setText("New Tournament");
        NewTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewTournamentButtonActionPerformed(evt);
            }
        });

        NameTextField.setText("Name");

        LocationTextField.setText("Location");

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        MessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        MessageLabel.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MessageLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NewTournamentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NameTextField)
                                .addComponent(LocationTextField, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(12, 12, 12)
                .addComponent(NewTournamentButton)
                .addGap(18, 18, 18)
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(MessageLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     */
    private void NewTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTournamentButtonActionPerformed
        Tournament newTourney = new Tournament(NameTextField.getText(), LocationTextField.getText());
        ArrayList<Tournament> tournamentList = new ArrayList<>(); 
        tournamentList = getTournaments();
        File outFile = new File("/Users/katidid/desktop/TOURNAMENTS.txt");
        tournamentList.add(newTourney); 
        try
        {
            FileWriter writer = new FileWriter(outFile, true);
            try
            {
                writer.write(newTourney.toString() + "\n");
                
            }
            catch(IOException ex)
            {
                MessageLabel.setText("Didn't output.");
            }
            writer.close();
        }
        catch(IOException ex)
        {
            MessageLabel.setText("Didn't make file");
        }

        firstMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_NewTournamentButtonActionPerformed
    public ArrayList<Tournament> getTournaments()
    {
        ArrayList<Tournament> tournamentList = new ArrayList<>();
        File outFile = new File("/Users/katidid/desktop/TOURNAMENTS.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(outFile))) 
        {
            String line = null;
            while ((line = reader.readLine()) != null) 
            {
                Tournament newTournament = parseNewTournament(line);  
                tournamentList.add(newTournament);    
            }
        } 
        catch (IOException x) 
        {
            System.err.format("IOException: %s%n", x);
        }
        return tournamentList;
    }
    /**
     * 
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        firstMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    public static Tournament parseNewTournament(String line)
    {
        Tournament newT = new Tournament();
        
        String phrase = line;
        String delims = ";";
        String[] phrases = phrase.split(delims);
        
        newT.setName(phrases[0].trim());
        newT.setLocation(phrases[1].trim());
        
//        int ID = Integer.parseInt(phrases[3].trim());
//        newJ.setId(ID);
        
        return newT;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LocationTextField;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton NewTournamentButton;
    private javax.swing.JButton backButton;
    // End of variables declaration//GEN-END:variables
}
