package javaapplication21;

import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author katidid
 */
public class TournamentMenu extends javax.swing.JFrame {
    Menu firstMenu;
    /**
     * Creates new form TournamentMenu
     */
    public TournamentMenu(Menu in) {
        initComponents();
        firstMenu = in;
    }
    
    private int onClose() {
        try{
        firstMenu.setVisible(true);
        dispose();
        }
        catch (NullPointerException e)
        {
            
        }
        return this.EXIT_ON_CLOSE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditTournamentButton = new javax.swing.JButton();
        GenerateTournamentButton = new javax.swing.JButton();
        ViewTournamentButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(onClose());

        EditTournamentButton.setBackground(new java.awt.Color(255, 102, 102));
        EditTournamentButton.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        EditTournamentButton.setText("Edit Tournament");
        EditTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTournamentButtonActionPerformed(evt);
            }
        });

        GenerateTournamentButton.setBackground(new java.awt.Color(255, 102, 102));
        GenerateTournamentButton.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        GenerateTournamentButton.setText("Generate Tournament");
        GenerateTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateTournamentButtonActionPerformed(evt);
            }
        });

        ViewTournamentButton.setBackground(new java.awt.Color(255, 102, 102));
        ViewTournamentButton.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        ViewTournamentButton.setText("View Tournament");
        ViewTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTournamentButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tournament 1", "Tournament 2", "Tournament 3" }));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GenerateTournamentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditTournamentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewTournamentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(EditTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenerateTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTournamentButtonActionPerformed
        // TODO add your handling code here:
        EditTournament mysim = new EditTournament();
        mysim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditTournamentButtonActionPerformed

    private void GenerateTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateTournamentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateTournamentButtonActionPerformed

    private void ViewTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTournamentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTournamentButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        firstMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditTournamentButton;
    private javax.swing.JButton GenerateTournamentButton;
    private javax.swing.JButton ViewTournamentButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
}
