package javaapplication21;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import static javaapplication21.NewTournament.parseNewTournament;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author katidid
 */
public class TournamentMenu extends javax.swing.JFrame {
    Menu firstMenu;
    /**
     * 
     * @param in 
     */
    public TournamentMenu(Menu in) {
        initComponents();
        firstMenu = in;
        ArrayList<Tournament> tournamentList = new ArrayList<>(); 
        tournamentList = getTournaments();
        getContentPane().setBackground(Color.darkGray);
        ViewTournamentButton.setVisible(false);
        for (int i = 0; i < tournamentList.size(); i++)
        {
            tournamentSelection.addItem(tournamentList.get(i));
        }
    }
    /**
     * 
     * @return 
     */
    private int onClose() {
        try{
        firstMenu.setVisible(true);
        dispose();
        }
        catch (NullPointerException e)
        {
            
        }
        return this.EXIT_ON_CLOSE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditTournamentButton = new javax.swing.JButton();
        GenerateTournamentButton = new javax.swing.JButton();
        ViewTournamentButton = new javax.swing.JButton();
        tournamentSelection = new javax.swing.JComboBox();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(onClose());

        EditTournamentButton.setBackground(new java.awt.Color(255, 102, 102));
        EditTournamentButton.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        EditTournamentButton.setText("Edit Tournament");
        EditTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTournamentButtonActionPerformed(evt);
            }
        });

        GenerateTournamentButton.setBackground(new java.awt.Color(255, 102, 102));
        GenerateTournamentButton.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        GenerateTournamentButton.setText("Generate Tournament");
        GenerateTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateTournamentButtonActionPerformed(evt);
            }
        });

        ViewTournamentButton.setBackground(new java.awt.Color(255, 102, 102));
        ViewTournamentButton.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        ViewTournamentButton.setText("View Tournament");
        ViewTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTournamentButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Cochin", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tournamentSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GenerateTournamentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditTournamentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewTournamentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tournamentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(EditTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenerateTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     */
    private void EditTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTournamentButtonActionPerformed
        // TODO add your handling code here:
        EditTournament mysim = new EditTournament(this, (Tournament)tournamentSelection.getSelectedItem());
        mysim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditTournamentButtonActionPerformed
    /**
     * 
     * @param evt 
     */
    private void GenerateTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateTournamentButtonActionPerformed
        RunTournament mysim = new RunTournament(this, (Tournament)tournamentSelection.getSelectedItem());
        mysim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GenerateTournamentButtonActionPerformed
    /**
     * 
     * @param evt 
     */
    private void ViewTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTournamentButtonActionPerformed
        ViewTournament mysim = new ViewTournament(this, (Tournament)tournamentSelection.getSelectedItem());
        mysim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewTournamentButtonActionPerformed
    /**
     * 
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        firstMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    /**
     * 
     * @return 
     */
    public ArrayList<Tournament> getTournaments()
    {
        ArrayList<Tournament> tournamentList = new ArrayList<>();
        File outFile = new File("TOURNAMENTS.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(outFile))) 
        {
            String line = null;
            while ((line = reader.readLine()) != null) 
            {
                Tournament newTournament = parseNewTournament(line);  
                tournamentList.add(newTournament);    
            }
        } 
        catch (IOException x) 
        {
            System.err.format("IOException: %s%n", x);
        }
        return tournamentList;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditTournamentButton;
    private javax.swing.JButton GenerateTournamentButton;
    private javax.swing.JButton ViewTournamentButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox tournamentSelection;
    // End of variables declaration//GEN-END:variables
}
