/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author katidid
 */
public class TournamentSimulator extends javax.swing.JFrame {
    TourneyController controller = new TourneyController();
    /**
     * Creates new form TournamentSimulator
     */
    public TournamentSimulator() {
        initComponents();
        populateListBox();
    }
    
    private void populateListBox()
    {
        File outFile = new File("/Users/katidid/desktop/EVENTS.txt");
        if (ListOfCompetitors.getModel().getSize() == 0)
        {
            try (BufferedReader reader = new BufferedReader(new FileReader(outFile))) 
            {
                String line = null;
                while ((line = reader.readLine()) != null) 
                {
                    Competitor newEvent = parseNewCompetitor(line);
                    
                    ((DefaultListModel)ListOfCompetitors.getModel()).addElement(newEvent);
                    
                }
            } 
            catch (IOException x) 
            {
                System.err.format("IOException: %s%n", x);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        newStudentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListOfCompetitors = new javax.swing.JList();
        NameTextField = new javax.swing.JTextField();
        SchoolTextField = new javax.swing.JTextField();
        NoviceButton = new javax.swing.JRadioButton();
        JuniorButton = new javax.swing.JRadioButton();
        SeniorButton = new javax.swing.JRadioButton();
        MessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newStudentButton.setText("Add competitor");
        newStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentButtonActionPerformed(evt);
            }
        });

        ListOfCompetitors.setModel(new DefaultListModel<Competitor>()
            {
                public int getSize(){
                    return controller.getNumComps();
                }
                public Competitor getElementAt(int i) {
                    return controller.getCompetitor(i);
                }
                public void addElement(Competitor e) {
                    super.addElement(e);
                    controller.addStu(e);
                }
                public void add(int i, Competitor e) {
                    super.add(i,e);
                    controller.addStu(e);
                }
            });
            jScrollPane1.setViewportView(ListOfCompetitors);

            NameTextField.setText("Name");

            SchoolTextField.setText("School");

            buttonGroup1.add(NoviceButton);
            NoviceButton.setText("Novice");

            buttonGroup1.add(JuniorButton);
            JuniorButton.setText("Junior");

            buttonGroup1.add(SeniorButton);
            SeniorButton.setText("Something");

            MessageLabel.setText("Message");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameTextField)
                            .addComponent(SchoolTextField))
                        .addComponent(NoviceButton)
                        .addComponent(JuniorButton)
                        .addComponent(SeniorButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60))
                .addGroup(layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SchoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(NoviceButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JuniorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SeniorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                            .addComponent(newStudentButton))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(25, 25, 25)
                    .addComponent(MessageLabel)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void newStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentButtonActionPerformed
        File studentOutFile = new File("/Users/katidid/desktop/COMPETITORS.txt");
//        try
//        {
            String name = NameTextField.getText();
            String school = SchoolTextField.getText();
            int level;
            if(NoviceButton.isSelected())
                level = 1;
            else if(JuniorButton.isSelected())
                level = 2;
            else if(SeniorButton.isSelected())
                level = 3;
            else
                level = 0;
        
            Competitor newStu = new Competitor(name, school, level);
            ((DefaultListModel)ListOfCompetitors.getModel()).addElement(newStu);
          
            try
            {
                FileWriter writer = new FileWriter(studentOutFile, true);
                try
                {
                    writer.write(newStu.toString() + "\n");
                }
                catch(IOException ex)
                {
                    MessageLabel.setText("Didn't output.");
                }
                writer.close();
            }
            catch(IOException ex)
            {
                MessageLabel.setText("Didn't make file");
            }
//        }
//        catch(NumberFormatException e) // If they don't fill out all the blanks properly
//        {
//            if (allFieldsFilled() == true)
//            {
//                MessageLabel.setText("Please don't mix numbers and words."); 
//            }
//            else
//            {
//                MessageLabel.setText("Please enter text in all boxes.");
//            }
//        }
//        populateListBox();
    }//GEN-LAST:event_newStudentButtonActionPerformed
public static Competitor parseNewCompetitor(String line)
    {
        Competitor newStu = new Competitor();
        
        String phrase = line;
        String delims = ";";
        String[] phrases = phrase.split(delims);
        
        newStu.setName(phrases[0]);
        newStu.setSchool(phrases[1]);
        
        int level = Integer.parseInt(phrases[2]);
        newStu.setLevel(level);
        
        return newStu;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TournamentSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JuniorButton;
    private javax.swing.JList ListOfCompetitors;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JRadioButton NoviceButton;
    private javax.swing.JTextField SchoolTextField;
    private javax.swing.JRadioButton SeniorButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newStudentButton;
    // End of variables declaration//GEN-END:variables
}
