/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author katidid
 */
public class TournamentSimulator extends javax.swing.JFrame {

    /**
     * Creates new form TournamentSimulator
     */
    public TournamentSimulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        newStudentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TheList = new javax.swing.JList();
        NameTextField = new javax.swing.JTextField();
        SchoolTextField = new javax.swing.JTextField();
        NoviceButton = new javax.swing.JRadioButton();
        JuniorButton = new javax.swing.JRadioButton();
        SeniorButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newStudentButton.setText("Add competitor");
        newStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentButtonActionPerformed(evt);
            }
        });

        TheList.setModel(new DefaultListModel<Competitor>()
            {
                public int getSize(){
                    return econtroller.getNumEvents();
                }
                public Event getElementAt(int i) {
                    return econtroller.getEvent(i);
                }
                public void addElement(Event e) {
                    super.addElement(e);
                    econtroller.addEvent(e);
                }
                public void add(int i, Event e) {
                    super.add(i,e);
                    econtroller.addEvent(e);
                }
            });
            jScrollPane1.setViewportView(TheList);

            NameTextField.setText("Name");
            NameTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NameTextFieldActionPerformed(evt);
                }
            });

            SchoolTextField.setText("School");
            SchoolTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SchoolTextFieldActionPerformed(evt);
                }
            });

            buttonGroup1.add(NoviceButton);
            NoviceButton.setText("Novice");
            NoviceButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NoviceButtonActionPerformed(evt);
                }
            });

            buttonGroup1.add(JuniorButton);
            JuniorButton.setText("Junior");
            JuniorButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JuniorButtonActionPerformed(evt);
                }
            });

            buttonGroup1.add(SeniorButton);
            SeniorButton.setText("Something");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameTextField)
                            .addComponent(SchoolTextField))
                        .addComponent(NoviceButton)
                        .addComponent(JuniorButton)
                        .addComponent(SeniorButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(23, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SchoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(NoviceButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JuniorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SeniorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(newStudentButton)
                    .addGap(47, 47, 47))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void SchoolTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SchoolTextFieldActionPerformed

    private void NoviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoviceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoviceButtonActionPerformed

    private void newStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentButtonActionPerformed
        File outFile = new File("/Users/katidid/desktop/EVENTS.txt");
//        try
//        {
            String name = NameTextField.getText();
            String school = SchoolTextField.getText();
            int level;
            if(NoviceButton.isSelected())
                level = 1;
            else if(JuniorButton.isSelected())
                level = 2;
            else if(SeniorButton.isSelected())
                level = 3;
            else
                level = 0;
//        
//            Competitor newStu = new Competitor(name, school, level);
//            ((DefaultListModel)ListOfEvents.getModel()).addElement(newEvent);
//            sortListByWhatever(econtroller.getEventList(), econtroller.getWhichSort());// sorts events by date
//            
//            try
//            {
//                FileWriter writer = new FileWriter(outFile, true);
//                econtroller.outputToFile(newEvent, writer);
//                writer.close();
//            }
//            catch(IOException ex)
//            {
//                MessageLabel.setText("Didn't make file");
//            }
//        }
//        catch(NumberFormatException e) // If they don't fill out all the blanks properly
//        {
//            if (allFieldsFilled() == true)
//            {
//                MessageLabel.setText("Please don't mix numbers and words."); 
//            }
//            else
//            {
//                MessageLabel.setText("Please enter text in all five boxes.");
//            }
//        }
//        populateListBox();
    }//GEN-LAST:event_newStudentButtonActionPerformed

    private void JuniorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuniorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JuniorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TournamentSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JuniorButton;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JRadioButton NoviceButton;
    private javax.swing.JTextField SchoolTextField;
    private javax.swing.JRadioButton SeniorButton;
    private javax.swing.JList TheList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newStudentButton;
    // End of variables declaration//GEN-END:variables
}
