/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam.pkg1;

/**
 *
 * @author katidid
 */
public class UnderOverGame extends javax.swing.JFrame {

    /**
     * Creates new form UnderOverGame
     */
    public UnderOverGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        P1BetText = new javax.swing.JTextField();
        WinnerLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        P1MoneyLabel = new javax.swing.JLabel();
        ChangeP1Button = new javax.swing.JButton();
        P1LoginText = new javax.swing.JTextField();
        Di1Label = new javax.swing.JLabel();
        Di2Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Place Bets and Roll!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        P1BetText.setEnabled(false);
        P1BetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1BetTextActionPerformed(evt);
            }
        });

        WinnerLabel.setText("___ won!");

        jLabel1.setText("Player 1 bets:");

        P1MoneyLabel.setText("Player 1 current money:");

        ChangeP1Button.setText("Change Player");
        ChangeP1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeP1ButtonActionPerformed(evt);
            }
        });

        P1LoginText.setText("Player1");
        P1LoginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1LoginTextActionPerformed(evt);
            }
        });

        Di1Label.setText("Di 1");

        Di2Label.setText("Di 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChangeP1Button)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(P1LoginText)))
                .addGap(4, 4, 4)
                .addComponent(Di1Label)
                .addGap(38, 38, 38)
                .addComponent(Di2Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(WinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(P1BetText)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(P1MoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(ChangeP1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P1LoginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(P1MoneyLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Di2Label)
                            .addComponent(Di1Label))
                        .addGap(40, 40, 40)))
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(P1BetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        RollDice roller = new RollDice();
        int Di1 = roller.getDi1();
        Di1Label.setText("Di 1: " + Di1);
        int Di2 = roller.getDi2();
        Di2Label.setText("Di 2: " + Di2);
        Player player1= new Player("John");
        cashingInBets(Di1, Di2, player1);
        refresh(player1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void P1BetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1BetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1BetTextActionPerformed

    private void P1LoginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1LoginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1LoginTextActionPerformed

    private void ChangeP1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeP1ButtonActionPerformed
        // TODO add your handling code here:
        P1BetText.enable();
    }//GEN-LAST:event_ChangeP1ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnderOverGame().setVisible(true);
            }
        });
    }
    /**
     * 
     * @param d1
     * @param d2
     * @param player 
     */
    
    public void cashingInBets(int d1, int d2, Player player)
    {
        int playerAmount = player.getAmount();
        int playerBet = player.getBet().getAmount();
        
        if (d1 + d2 < 7)
        {
            if (player.getBet().getBetOutcome() <= 7)
            { 
                player.setAmount(playerAmount+=playerBet);
            }
            else
            {
                player.setAmount(playerAmount-=playerBet);
            }
        }
        else if (d1 + d2 > 7)
        {
            if (player.getBet().getBetOutcome() >= 7)
            { 
                player.setAmount(playerAmount+=playerBet);
            }
            else
            {
                player.setAmount(playerAmount-=playerBet);
            }
        }
        else
        {
            if (player.getBet().getBetOutcome() == 7)
            { 
                player.setAmount(playerAmount+=(playerBet*4));
            }
            else
            {
                player.setAmount(playerAmount-=(playerBet*4));
            }
        }
    }
    /**
     * 
     */
    public void refresh(Player p1) // a method used to refresh the page, in a sense, after
            // bets are chashed and so forth; so, updating the amounts, clearing
            // the bet texts, etc.
    {
        P1BetText.setText(null);
        P1MoneyLabel.setText("P1 money");
        WinnerLabel.setText("who's the winner?");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeP1Button;
    private javax.swing.JLabel Di1Label;
    private javax.swing.JLabel Di2Label;
    private javax.swing.JTextField P1BetText;
    private javax.swing.JTextField P1LoginText;
    private javax.swing.JLabel P1MoneyLabel;
    private javax.swing.JLabel WinnerLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
