/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam.pkg1;

/**
 *
 * @author kshaw
 */
public class UnderOverGame extends javax.swing.JFrame {

    /**
     * Creates new form UnderOverGame
     */
    public UnderOverGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        LessThanButton = new javax.swing.JRadioButton();
        GreaterThanButton = new javax.swing.JRadioButton();
        EqualButton = new javax.swing.JRadioButton();
        MainButton = new javax.swing.JButton();
        P1BetText = new javax.swing.JTextField();
        WinnerLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        P1MoneyLabel = new javax.swing.JLabel();
        ChangeP1Button = new javax.swing.JButton();
        P1LoginText = new javax.swing.JTextField();
        Di1Label = new javax.swing.JLabel();
        Di2Label = new javax.swing.JLabel();
        PlayerNameLabel = new javax.swing.JLabel();
        BetOutcomeText = new javax.swing.JTextField();
        MessageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        LessThanButton.setText("<7");

        GreaterThanButton.setText(">7");
        GreaterThanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreaterThanButtonActionPerformed(evt);
            }
        });

        EqualButton.setText("=7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainButton.setText("Log In");
        MainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainButtonActionPerformed(evt);
            }
        });

        P1BetText.setEnabled(false);
        P1BetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1BetTextActionPerformed(evt);
            }
        });

        WinnerLabel.setText("___ won!");

        jLabel1.setText("Player 1 bets:");

        P1MoneyLabel.setText("Player 1 current money:");

        ChangeP1Button.setText("Change Player");
        ChangeP1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeP1ButtonActionPerformed(evt);
            }
        });

        P1LoginText.setText("Player1");
        P1LoginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1LoginTextActionPerformed(evt);
            }
        });

        Di1Label.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        Di1Label.setText("Di 1");

        Di2Label.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        Di2Label.setText("Di 2");

        PlayerNameLabel.setText("NAME");

        BetOutcomeText.setEnabled(false);
        BetOutcomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetOutcomeTextActionPerformed(evt);
            }
        });

        MessageLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N

        jLabel2.setText("Type your name and press \"Log In\" to log in!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlayerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Di1Label)
                        .addGap(31, 31, 31)
                        .addComponent(Di2Label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(P1MoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(WinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(P1BetText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BetOutcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(MainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(P1LoginText)
                            .addComponent(ChangeP1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MessageLabel)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChangeP1Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P1LoginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerNameLabel)
                    .addComponent(Di1Label)
                    .addComponent(Di2Label))
                .addGap(18, 18, 18)
                .addComponent(P1MoneyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1BetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BetOutcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 */
    private void MainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainButtonActionPerformed
        //if(MainButton.getText() == "Log In")
        //{
            Player player1= new Player(P1LoginText.getText());
            MainButton.setText("Roll Dice!");
            P1BetText.enable();
            BetOutcomeText.enable();
        //}
        
        //else{
        try
        {
            RollDice roller = new RollDice();
            int Di1 = roller.getDi1();
            Di1Label.setText("Di 1: " + Di1);
            int Di2 = roller.getDi2();
            Di2Label.setText("Di 2: " + Di2);
            //Player player1= new Player("John");
            
            
            try{
                int betOutcome = Integer.parseInt(BetOutcomeText.getText());
                player1.getBet().setBetOutcome(betOutcome);
            }
            catch(NullPointerException e)
            {
                MessageLabel.setText(e.getMessage());
            }
            catch(IllegalArgumentException ex)
            {
               MessageLabel.setText(ex.getMessage());
            }
            
        
            int betPlayerOutcome = Integer.parseInt(BetOutcomeText.getText());
            int betAmount = Integer.parseInt(P1BetText.getText());
            Bet bet = new Bet(betAmount, betPlayerOutcome);
            player1.addBet(bet);
        
            cashingInBets(Di1, Di2, player1);
            refresh(player1);
        }
        catch(NumberFormatException e)
        {
            if (MainButton.getText() != "Log In")
                MessageLabel.setText("!Please place correct bets!");
        }
        //}
    }//GEN-LAST:event_MainButtonActionPerformed

    private void P1BetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1BetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1BetTextActionPerformed

    private void P1LoginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1LoginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1LoginTextActionPerformed

    private void ChangeP1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeP1ButtonActionPerformed
        // TODO add your handling code here:
        P1BetText.disable();
        BetOutcomeText.disable();
        MainButton.setText( "Log In");
        
    }//GEN-LAST:event_ChangeP1ButtonActionPerformed

    private void BetOutcomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetOutcomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BetOutcomeTextActionPerformed

    private void GreaterThanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreaterThanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GreaterThanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnderOverGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnderOverGame().setVisible(true);
            }
        });
    }
    /**
     * 
     * @param d1
     * @param d2
     * @param player 
     */
    
    public void cashingInBets(int d1, int d2, Player player)
    {
        int playerAmount = player.getAmount();
        int playerBet = player.getBet().getAmount();
        int DiRoll = d1 + d2;

        if (player.won(DiRoll)==true) // if player won
        { 
            if(d1+d2 == 7)
            {
                player.setAmount(playerAmount+=playerBet);
            }
            else
                player.setAmount(playerAmount+=(playerBet*4));
        }   
        else // if player lost
        {
            if(d1+d2 == 7)
            {
                player.setAmount(playerAmount-=(playerBet*4));
            }
            else
                player.setAmount(playerAmount-=playerBet);
        }
        
    }
    /**
     * 
     * @param p1 
     */
    public void refresh(Player p1) // a method used to refresh the page, in a sense, after
            // bets are chashed and so forth; so, updating the amounts, clearing
            // the bet texts, etc.
    {
        P1BetText.setText(null); //clears
        P1MoneyLabel.setText("Current money: " + p1.getAmount());
        WinnerLabel.setText("who's the winner?");
        PlayerNameLabel.setText(p1.getName());
        BetOutcomeText.setText(null);
        MessageLabel.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BetOutcomeText;
    private javax.swing.JButton ChangeP1Button;
    private javax.swing.JLabel Di1Label;
    private javax.swing.JLabel Di2Label;
    private javax.swing.JRadioButton EqualButton;
    private javax.swing.JRadioButton GreaterThanButton;
    private javax.swing.JRadioButton LessThanButton;
    private javax.swing.JButton MainButton;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField P1BetText;
    private javax.swing.JTextField P1LoginText;
    private javax.swing.JLabel P1MoneyLabel;
    private javax.swing.JLabel PlayerNameLabel;
    private javax.swing.JLabel WinnerLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
